# Configurações do alvo
TARGET_IP="192.168.1.18"
TARGET_PORTS="21,22,80,445,139"

# Wordlists padrão
USERS_WORDLIST="../wordlists/users.txt"
PASS_WORDLIST="../wordlists/pass.txt"
SMB_USERS_WORDLIST="../wordlists/smb_users.txt"
SMB_PASS_WORDLIST="../wordlists/senhas_spray.txt"
